install:
  - sudo add-apt-repository ppa:texlive-backports/ppa -y
  - sudo apt-get update
  - sudo apt-get install texlive texlive-latex-extra texlive-math-extra -y --fix-missing

script: "make"

notifications:
  - email: true

branches:
  only:
    - master