install:
  - sudo add-apt-repository ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install texlive --fix-missing

script: "make"

notifications:
  - email: true

branches:
  only:
    - master